/* GeneratedCorpusQueryLanguageParser.java */
/* Generated By:JavaCC: Do not edit this line. GeneratedCorpusQueryLanguageParser.java */
package nl.inl.blacklab.queryParser.corpusql;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import nl.inl.blacklab.search.indexmetadata.MatchSensitivity;
import nl.inl.blacklab.search.lucene.BLSpanQuery;
import nl.inl.blacklab.search.lucene.SpanQueryPositionFilter.Operation;
import nl.inl.blacklab.search.matchfilter.MatchFilter;
import nl.inl.blacklab.search.matchfilter.MatchFilterAnd;
import nl.inl.blacklab.search.matchfilter.MatchFilterEquals;
import nl.inl.blacklab.search.matchfilter.MatchFilterImplication;
import nl.inl.blacklab.search.matchfilter.MatchFilterNot;
import nl.inl.blacklab.search.matchfilter.MatchFilterOr;
import nl.inl.blacklab.search.matchfilter.MatchFilterString;
import nl.inl.blacklab.search.matchfilter.MatchFilterTokenProperty;
import nl.inl.blacklab.search.textpattern.TextPattern;
import nl.inl.blacklab.search.textpattern.TextPatternAnd;
import nl.inl.blacklab.search.textpattern.TextPatternAnyToken;
import nl.inl.blacklab.search.textpattern.TextPatternCaptureGroup;
import nl.inl.blacklab.search.textpattern.TextPatternConstrained;
import nl.inl.blacklab.search.textpattern.TextPatternEdge;
import nl.inl.blacklab.search.textpattern.TextPatternNot;
import nl.inl.blacklab.search.textpattern.TextPatternOr;
import nl.inl.blacklab.search.textpattern.TextPatternPositionFilter;
import nl.inl.blacklab.search.textpattern.TextPatternQueryFunction;
import nl.inl.blacklab.search.textpattern.TextPatternRepetition;
import nl.inl.blacklab.search.textpattern.TextPatternSequence;
import nl.inl.blacklab.search.textpattern.TextPatternTags;

@SuppressWarnings("all")

public class GeneratedCorpusQueryLanguageParser implements GeneratedCorpusQueryLanguageParserConstants {

    CorpusQueryLanguageParser wrapper;

// --- Grammar rules start here --- 

/* a query */
  final public TextPattern query() throws ParseException {TextPattern a = null;
    a = constrainedQuery();
    jj_consume_token(0);
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern constrainedQuery() throws ParseException {TextPattern a = null;
        MatchFilter b = null;
    a = complexQuery();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 14:{
      jj_consume_token(14);
      b = constraint();
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
if (b == null)
            {if ("" != null) return a;}
        {if ("" != null) return new TextPatternConstrained(a, b);}
    throw new Error("Missing return statement in function");
  }

  final public MatchFilter constraint() throws ParseException {MatchFilter a = null, c = null;
    Token b = null;
    a = simpleConstraint();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 30:
    case 31:
    case 32:{
      b = booleanOperator();
      c = constraint();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
if (b == null)
                        {if ("" != null) return a;}
        if (b.toString().equals("->"))
            {if ("" != null) return new MatchFilterImplication(a, c);}
                if (b.toString().equals("&"))
                        {if ("" != null) return new MatchFilterAnd(a, c);}
                {if ("" != null) return new MatchFilterOr(a, c);}
    throw new Error("Missing return statement in function");
  }

  final public MatchFilter simpleConstraint() throws ParseException {MatchFilter v = null, w = null;
    Token b = null;
    v = constraintValue();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 15:
    case 16:{
      b = equalityOperator();
      w = constraintValue();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
if (b == null)
                        {if ("" != null) return v;}
        if (b.toString().equals("="))
            {if ("" != null) return new MatchFilterEquals(v, w, MatchSensitivity.INSENSITIVE);}
                if (b.toString().equals("!="))
                        {if ("" != null) return new MatchFilterNot(new MatchFilterEquals(v, w, MatchSensitivity.INSENSITIVE));}
    throw new Error("Missing return statement in function");
  }

  final public Token equalityOperator() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 15:{
      t = jj_consume_token(15);
      break;
      }
    case 16:{
      t = jj_consume_token(16);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

  final public MatchFilter constraintValue() throws ParseException {MatchFilter v = null;
        String q = null;
        Token s = null;
        String l = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:{
      q = quotedString();
{if ("" != null) return new MatchFilterString(q);}
      break;
      }
    case 17:{
      jj_consume_token(17);
      v = constraint();
      jj_consume_token(18);
{if ("" != null) return v;}
      break;
      }
    case 19:{
      jj_consume_token(19);
      v = constraintValue();
{if ("" != null) return new MatchFilterNot(v);}
      break;
      }
    case NAME:
    case NUMBER:{
      l = captureLabel();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 20:{
        jj_consume_token(20);
        s = jj_consume_token(NAME);
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        ;
      }
{if ("" != null) return new MatchFilterTokenProperty(l, s == null ? null : s.toString());}
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern complexQuery() throws ParseException {TextPattern a = null, b = null;
    Token op = null;
    Operation oper = Operation.CONTAINING;
    a = simpleQuery();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WITHIN:
    case CONTAINING:{
      op = queryOperator();
      b = complexQuery();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
if (op == null)
            {if ("" != null) return a;}
        if (op.toString().equals("within")) {
            // a within b
            oper = Operation.WITHIN;
        }

        {if ("" != null) return new TextPatternPositionFilter(a, b, oper);}
    throw new Error("Missing return statement in function");
  }

  final public Token queryOperator() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WITHIN:{
      t = jj_consume_token(WITHIN);
      break;
      }
    case CONTAINING:{
      t = jj_consume_token(CONTAINING);
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

/* a simple query (not including containing, within, etc.) */
  final public TextPattern simpleQuery() throws ParseException {TextPattern query = null, rest = null;
    Token b = null;
    query = sequence();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 30:
    case 31:
    case 32:{
      b = booleanOperator();
      rest = simpleQuery();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
if (b == null)
                        {if ("" != null) return query;}
        if (b.toString().equals("->"))
            {if (true) throw new UnsupportedOperationException("Implication operator only supported within global constraints");}
                if (b.toString().equals("&"))
                        {if ("" != null) return new TextPatternAnd(query, rest);}
                {if ("" != null) return new TextPatternOr(query, rest);}
    throw new Error("Missing return statement in function");
  }

/* a sequence of token constraints */
  final public TextPattern sequence() throws ParseException {TextPattern first = null;
        TextPattern result = null;
        TextPattern[] tag = null;
    Token t2 = null;
    first = sequencePart();
    if (jj_2_1(2)) {
      result = sequenceRest(first);
    } else {
      ;
    }
if (result == null)
                        result = first;

                {if ("" != null) return result;}
    throw new Error("Missing return statement in function");
  }

/* a start or self-closing tag tag such as <s> or <s/> (for finding XML elements).
 * Note that it returns one TextPattern, but if it's in [0] that means it's a start
 * tag; if it's in [1] it's a self-closing tag.
 */
  final public TextPattern tag() throws ParseException {Token tagName, endTagSlash = null, selfCloseSlash = null;
    Map<String, String> attr = new HashMap<String, String>();
    jj_consume_token(21);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 22:{
      endTagSlash = jj_consume_token(22);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    tagName = jj_consume_token(NAME);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_1;
      }
      attributes(attr);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 22:{
      selfCloseSlash = jj_consume_token(22);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(23);
if (endTagSlash != null && selfCloseSlash != null) {
            {if (true) throw new MalformedTagException();}
        }
        TextPattern tags = new TextPatternTags(tagName.toString(), attr);
        if (selfCloseSlash != null)
            {if ("" != null) return tags;}
        if (endTagSlash != null) {
            if (attr.size() > 0) {
                {if (true) throw new MalformedTagException("Cannot filter XML end tag on attributes");}
            }
            {if ("" != null) return new TextPatternEdge(tags, true);} // right edge
        }
        {if ("" != null) return new TextPatternEdge(tags, false);} // left edge

    throw new Error("Missing return statement in function");
  }

  final public String quotedString() throws ParseException {Token a;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:{
      a = jj_consume_token(QUOTED_STRING);
      break;
      }
    case SINGLE_QUOTED_STRING:{
      a = jj_consume_token(SINGLE_QUOTED_STRING);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return wrapper.getStringBetweenQuotes(a.toString());}
    throw new Error("Missing return statement in function");
  }

  final public void attributes(Map<String, String> attr) throws ParseException {Token name;
    String value;
    name = jj_consume_token(NAME);
    jj_consume_token(15);
    value = quotedString();
attr.put(name.toString(), value);
  }

/* continuation of a sequence (after the first part) */
  final public TextPattern sequenceRest(TextPattern first) throws ParseException {Token op = null;
        TextPattern rest = null;
    rest = sequence();
if (rest == null)
                        {if ("" != null) return first;}
                {if ("" != null) return new TextPatternSequence(first, rest);}
    throw new Error("Missing return statement in function");
  }

/* a repetition specifier */
  final public Integer[] repetitionAmount() throws ParseException {Token t = null, t2 = null;
        Integer[] minMax = new Integer[2];
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 24:{
      jj_consume_token(24);
minMax[0] = 0; minMax[1] = BLSpanQuery.MAX_UNLIMITED; {if ("" != null) return minMax;}
      break;
      }
    case 25:{
      jj_consume_token(25);
minMax[0] = 1; minMax[1] = BLSpanQuery.MAX_UNLIMITED; {if ("" != null) return minMax;}
      break;
      }
    case 26:{
      jj_consume_token(26);
minMax[0] = 0; minMax[1] = 1; {if ("" != null) return minMax;}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      if (jj_2_2(3)) {
        jj_consume_token(27);
        t = jj_consume_token(NUMBER);
        jj_consume_token(28);
minMax[0] = minMax[1] = wrapper.num(t); {if ("" != null) return minMax;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 27:{
          jj_consume_token(27);
          t = jj_consume_token(NUMBER);
          jj_consume_token(29);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case NUMBER:{
            t2 = jj_consume_token(NUMBER);
            break;
            }
          default:
            jj_la1[13] = jj_gen;
            ;
          }
          jj_consume_token(28);
minMax[0] = wrapper.num(t);
                if (t2 == null)
                        minMax[1] = BLSpanQuery.MAX_UNLIMITED;
                else
                        minMax[1] = wrapper.num(t2);
                {if ("" != null) return minMax;}
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

/* boolean operator: and, or or implication */
  final public Token booleanOperator() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 30:{
      t = jj_consume_token(30);
      break;
      }
    case 31:{
      t = jj_consume_token(31);
      break;
      }
    case 32:{
      t = jj_consume_token(32);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

/* sequence part: one part in a sequence, possibly with a repetition operator */
  final public TextPattern sequencePart() throws ParseException {TextPattern m = null;
        Integer[] rep = null;
        String label = null;
    if (jj_2_5(2)) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 21:{
        m = tag();
        break;
        }
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case 34:{
        m = position();
        break;
        }
      case 17:{
        jj_consume_token(17);
        m = complexQuery();
        jj_consume_token(18);
        break;
        }
      case NAME:{
        m = queryFunctionCall();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (jj_2_3(6)) {
        rep = repetitionAmount();
      } else {
        ;
      }
if (rep != null)
        {
            if (m instanceof TextPatternAnyToken)
            {
                TextPatternAnyToken any = (TextPatternAnyToken)m;
                m = any.repeat(rep[0], rep[1]);
            } else
                m = new TextPatternRepetition(m, rep[0], rep[1]);
        }
        if (label != null) {
            m = new TextPatternCaptureGroup(m, label);
        }
        {if ("" != null) return m;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:
      case NUMBER:{
        label = captureLabel();
        jj_consume_token(33);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 21:{
          m = tag();
          break;
          }
        case QUOTED_STRING:
        case SINGLE_QUOTED_STRING:
        case 34:{
          m = position();
          break;
          }
        case 17:{
          jj_consume_token(17);
          m = complexQuery();
          jj_consume_token(18);
          break;
          }
        case NAME:{
          m = queryFunctionCall();
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        if (jj_2_4(6)) {
          rep = repetitionAmount();
        } else {
          ;
        }
if (rep != null)
                {
            if (m instanceof TextPatternAnyToken)
            {
                TextPatternAnyToken any = (TextPatternAnyToken)m;
                m = any.repeat(rep[0], rep[1]);
            } else
                m = new TextPatternRepetition(m, rep[0], rep[1]);
                }
                if (label != null) {
                    m = new TextPatternCaptureGroup(m, label);
                }
                {if ("" != null) return m;}
        break;
        }
      default:
        jj_la1[19] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern queryFunctionCall() throws ParseException {Token func = null;
    List<TextPattern> queryFuncParamList;
    func = jj_consume_token(NAME);
    jj_consume_token(17);
    queryFuncParamList = commaSeparatedListOfQueries();
    jj_consume_token(18);
String funcName = func.toString();
        if (!funcName.startsWith("_")) {
            {if (true) throw new UnsupportedOperationException("Query functions are a BlackLab-specific extension to Corpus Query Language and, to avoid future problems, must start with '_' !");}
        }
        {if ("" != null) return new TextPatternQueryFunction(funcName, queryFuncParamList);}
    throw new Error("Missing return statement in function");
  }

  final public List<TextPattern> commaSeparatedListOfQueries() throws ParseException {TextPattern q = null;
    List<TextPattern> p = new ArrayList<TextPattern>();
    q = complexQuery();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 29:{
      jj_consume_token(29);
      p = commaSeparatedListOfQueries();
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      ;
    }
p.add(0, q);
        {if ("" != null) return p;}
    throw new Error("Missing return statement in function");
  }

  final public String captureLabel() throws ParseException {Token l = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NAME:{
      l = jj_consume_token(NAME);
      break;
      }
    case NUMBER:{
      l = jj_consume_token(NUMBER);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return l.toString();}
    throw new Error("Missing return statement in function");
  }

/* position: a simple attribute value or complex attribute expression between square brackets */
  final public TextPattern position() throws ParseException {TextPattern m = null;
        String f = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:{
      m = positionWord();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FLAGS:{
        f = flags();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        ;
      }
{if ("" != null) return m;}
      break;
      }
    case 34:{
      jj_consume_token(34);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case 17:
      case 19:{
        m = positionLong();
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        ;
      }
      jj_consume_token(35);
if (m == null)
            {if ("" != null) return new TextPatternAnyToken(1, 1);}
        {if ("" != null) return m;}
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String flags() throws ParseException {Token f;
    f = jj_consume_token(FLAGS);
{if ("" != null) return f.toString().substring(1);}
    throw new Error("Missing return statement in function");
  }

/* position word: no brackets, just a single token constraint for the default attribute (usually word form) */
  final public TextPattern positionWord() throws ParseException {String t = null;
    t = quotedString();
{if ("" != null) return wrapper.simplePattern(t);}
    throw new Error("Missing return statement in function");
  }

/* expression inside square brackets: an attribute clause, or multiple 
   attribute clauses combined with boolean operators */
  final public TextPattern positionLong() throws ParseException {TextPattern a = null, c = null;
        Token b = null;
    a = positionLongPart();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 30:
    case 31:
    case 32:{
      b = booleanOperator();
      c = positionLong();
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      ;
    }
if (b == null)
                        {if ("" != null) return a;}
        if (b.toString().equals("->"))
            {if (true) throw new UnsupportedOperationException("Implication operator only supported within global constraints");}
                if (b.toString().equals("&"))
                        {if ("" != null) return new TextPatternAnd(a, c);}
                {if ("" != null) return new TextPatternOr(a, c);}
    throw new Error("Missing return statement in function");
  }

/* attribute clause: an attribute/value pair, attribute expression between parens, or a negated attribute/value pair */
  final public TextPattern positionLongPart() throws ParseException {TextPattern m = null;
    if (jj_2_6(3)) {
      m = attValuePair();
{if ("" != null) return m;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 17:{
        jj_consume_token(17);
        m = positionLong();
        jj_consume_token(18);
{if ("" != null) return m;}
        break;
        }
      case 19:{
        jj_consume_token(19);
        m = positionLongPart();
{if ("" != null) return new TextPatternNot(m);}
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

/* attribute/value pair, with equals or not equals sign, or possibly just a value (default attribute) */
  final public TextPattern attValuePair() throws ParseException {TextPattern v = null;
        String annot;
        String f = null;
    if (jj_2_7(2)) {
      annot = propName();
      jj_consume_token(15);
      v = valuePart();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FLAGS:{
        f = flags();
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        ;
      }
{if ("" != null) return wrapper.annotationClause(annot, v);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:{
        annot = propName();
        jj_consume_token(16);
        v = valuePart();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FLAGS:{
          f = flags();
          break;
          }
        default:
          jj_la1[28] = jj_gen;
          ;
        }
{if ("" != null) return new TextPatternNot(wrapper.annotationClause(annot, v));}
        break;
        }
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case 17:{
        v = valuePart();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FLAGS:{
          f = flags();
          break;
          }
        default:
          jj_la1[29] = jj_gen;
          ;
        }
{if ("" != null) return v;}
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String propName() throws ParseException {Token t = null, subAnnot = null;
    t = jj_consume_token(NAME);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 22:{
      jj_consume_token(22);
      subAnnot = jj_consume_token(NAME);
      break;
      }
    default:
      jj_la1[31] = jj_gen;
      ;
    }
String propName = t.toString();
                if (subAnnot == null)
                        {if ("" != null) return propName;}
                {if ("" != null) return propName + "/" + subAnnot.toString();}
    throw new Error("Missing return statement in function");
  }

/* value expression: a value or multiple values combined with boolean operators */
  final public TextPattern value() throws ParseException {TextPattern a = null, c = null;
        Token b = null;
    if (jj_2_8(3)) {
      a = valuePart();
      b = booleanOperator();
      c = value();
if (b.toString().equals("->"))
            {if (true) throw new UnsupportedOperationException("Implication operator only supported within global constraints");}
                if (b.toString().equals("&"))
                        {if ("" != null) return new TextPatternAnd(a, c);}
                {if ("" != null) return new TextPatternOr(a, c);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case 17:{
        a = valuePart();
{if ("" != null) return a;}
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

/* value: a quoted string, a value expression between parens, or a negated value */
  final public TextPattern valuePart() throws ParseException {TextPattern m = null;
        String t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:{
      t = quotedString();
{if ("" != null) return wrapper.simplePattern(t);}
      break;
      }
    case 17:{
      jj_consume_token(17);
      m = value();
      jj_consume_token(18);
{if ("" != null) return m;}
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_3R_26()
 {
    if (jj_scan_token(17)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(18)) return true;
    return false;
  }

  private boolean jj_3R_10()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) return true;
    }
    return false;
  }

  private boolean jj_3R_25()
 {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_38()
 {
    if (jj_scan_token(FLAGS)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_2()) return true;
    return false;
  }

  private boolean jj_3R_4()
 {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_18()
 {
    if (jj_scan_token(21)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(22)) jj_scanpos = xsp;
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_4()) {
    jj_scanpos = xsp;
    if (jj_3R_5()) {
    jj_scanpos = xsp;
    if (jj_3R_6()) {
    jj_scanpos = xsp;
    if (jj_3R_7()) return true;
    }
    }
    }
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) return true;
    }
    return false;
  }

  private boolean jj_3R_37()
 {
    if (jj_3R_40()) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    if (jj_scan_token(34)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) jj_scanpos = xsp;
    if (jj_scan_token(35)) return true;
    return false;
  }

  private boolean jj_3R_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_scan_token(32)) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_3R_35()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) return true;
    }
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_10()) return true;
    if (jj_3R_11()) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_12()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_scan_token(22)) return true;
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_13()
 {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(11)) return true;
    }
    return false;
  }

  private boolean jj_3R_17()
 {
    if (jj_scan_token(27)) return true;
    if (jj_scan_token(NUMBER)) return true;
    if (jj_scan_token(29)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(11)) jj_scanpos = xsp;
    if (jj_scan_token(28)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(27)) return true;
    if (jj_scan_token(NUMBER)) return true;
    if (jj_scan_token(28)) return true;
    return false;
  }

  private boolean jj_3R_16()
 {
    if (jj_scan_token(26)) return true;
    return false;
  }

  private boolean jj_3R_9()
 {
    if (jj_scan_token(NAME)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_15()
 {
    if (jj_scan_token(25)) return true;
    return false;
  }

  private boolean jj_3R_3()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_14()) {
    jj_scanpos = xsp;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_14()
 {
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_23()
 {
    if (jj_3R_10()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_22()
 {
    if (jj_3R_9()) return true;
    if (jj_scan_token(16)) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_8()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_9()) return true;
    if (jj_scan_token(15)) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_7()
 {
    if (jj_3R_21()) return true;
    return false;
  }

  private boolean jj_3R_2()
 {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_43()
 {
    if (jj_scan_token(19)) return true;
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_scan_token(17)) return true;
    return false;
  }

  private boolean jj_3R_41()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(17)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_6()
 {
    if (jj_scan_token(17)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  private boolean jj_3R_40()
 {
    if (jj_3R_41()) return true;
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_3R_31()) return true;
    return false;
  }

  private boolean jj_3R_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(12)) {
    jj_scanpos = xsp;
    if (jj_scan_token(13)) return true;
    }
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_3R_39()) return true;
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_5()
 {
    if (jj_3R_19()) return true;
    return false;
  }

  private boolean jj_3R_36()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GeneratedCorpusQueryLanguageParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[34];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4000,0xc0000000,0x18000,0x18000,0x100000,0xa3a00,0x180,0x180,0xc0000000,0x400000,0x200,0x400000,0x3000,0x800,0x7000000,0x8000000,0xc0000000,0x223200,0x223200,0xa00,0x20000000,0xa00,0x400,0xa3200,0x3000,0xc0000000,0xa0000,0x400,0x400,0x400,0x23200,0x400000,0x23000,0x23000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x4,0x4,0x0,0x0,0x0,0x0,0x0,0x4,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[8];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GeneratedCorpusQueryLanguageParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GeneratedCorpusQueryLanguageParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GeneratedCorpusQueryLanguageParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GeneratedCorpusQueryLanguageParser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new GeneratedCorpusQueryLanguageParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
      jj_input_stream = new JavaCharStream(stream, 1, 1);
   } else {
      jj_input_stream.ReInit(stream, 1, 1);
   }
   if (token_source == null) {
      token_source = new GeneratedCorpusQueryLanguageParserTokenManager(jj_input_stream);
   }

    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GeneratedCorpusQueryLanguageParser(GeneratedCorpusQueryLanguageParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GeneratedCorpusQueryLanguageParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) {
       return;
    }

    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];

      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }

      for (int[] oldentry : jj_expentries) {
        if (oldentry.length == jj_expentry.length) {
          boolean isMatched = true;

          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              isMatched = false;
              break;
            }

          }
          if (isMatched) {
            jj_expentries.add(jj_expentry);
            break;
          }
        }
      }

      if (pos != 0) {
        jj_lasttokens[(jj_endpos = pos) - 1] = kind;
      }
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[36];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 34; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 36; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 8; i++) {
      try {
        JJCalls p = jj_2_rtns[i];

        do {
          if (p.gen > jj_gen) {
            jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
            switch (i) {
              case 0: jj_3_1(); break;
              case 1: jj_3_2(); break;
              case 2: jj_3_3(); break;
              case 3: jj_3_4(); break;
              case 4: jj_3_5(); break;
              case 5: jj_3_6(); break;
              case 6: jj_3_7(); break;
              case 7: jj_3_8(); break;
            }
          }
          p = p.next;
        } while (p != null);

        } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }

    p.gen = jj_gen + xla - jj_la; 
    p.first = token;
    p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
