/* Generated By:JavaCC: Do not edit this line. GeneratedCorpusQueryLanguageParserConstants.java */
package nl.inl.blacklab.queryParser.corpusql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GeneratedCorpusQueryLanguageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WITHIN = 7;
  /** RegularExpression Id. */
  int CONTAINING = 8;
  /** RegularExpression Id. */
  int OVERLAP = 9;
  /** RegularExpression Id. */
  int IN = 10;
  /** RegularExpression Id. */
  int DEFAULT_VALUE = 11;
  /** RegularExpression Id. */
  int ROOT_DEP_OP = 12;
  /** RegularExpression Id. */
  int DEP_OP = 13;
  /** RegularExpression Id. */
  int ALIGNMENT_OP = 14;
  /** RegularExpression Id. */
  int QUOTED_STRING = 15;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 16;
  /** RegularExpression Id. */
  int NAME = 17;
  /** RegularExpression Id. */
  int FLAGS = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int SETTINGS_OP = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"within\"",
    "\"containing\"",
    "\"overlap\"",
    "\"in\"",
    "\"_\"",
    "<ROOT_DEP_OP>",
    "<DEP_OP>",
    "<ALIGNMENT_OP>",
    "<QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "<NAME>",
    "<FLAGS>",
    "<NUMBER>",
    "<SETTINGS_OP>",
    "\"::\"",
    "\"=\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"/\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"{\"",
    "\"}\"",
    "\"&\"",
    "\"|\"",
    "\"->\"",
  };

}
