package nl.inl.blacklab.search;

/**
 * A RuntimeException generated by BlackLab.
 *
 * This will be the base class of all BlackLab-thrown RuntimeExceptions.
 * More specific subclasses can be caught to handle specific situations.
 */
public class BLRuntimeException extends RuntimeException {

	public BLRuntimeException() {
		super();
	}

	public BLRuntimeException(String message, Throwable cause,
			boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
	}

	public BLRuntimeException(String message, Throwable cause) {
		super(message, cause);
	}

	public BLRuntimeException(String message) {
		super(message);
	}

	public BLRuntimeException(Throwable cause) {
		super(cause);
	}

}
