version: '3.9'

services:

  proxy:
    build:
      context: ..
      dockerfile: proxy/Dockerfile

    volumes:
      # Configuration file
      - ./testdata/proxy.yaml:/etc/blacklab/proxy.yaml

    ports:
      # Use port 8080 so it's the same exact URL as BLS would be (for running the same tests)
      - "8080:8080"

  # Solr backend we proxy to
  solr:
    build:
      context: ..
      dockerfile: solr/Dockerfile

    ports:
        - "8983:8983"
