version: '3.9'

services:

  proxy:
    build:
      context: ..
      dockerfile: proxy/Dockerfile
    volumes:
      - ./testdata/aggregator.yaml:/etc/blacklab/aggregator.yaml
    ports:
      - "8084:8080"
    depends_on:
      - node1
      - node2
