/* Generated By:JavaCC: Do not edit this line. CorpusQueryLanguageParserConstants.java */
package nl.inl.blacklab.queryParser.corpusql;

public interface CorpusQueryLanguageParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int MULTI_LINE_COMMENT = 6;
  int WITHIN = 7;
  int CONTAINING = 8;
  int NAME = 9;
  int NUMBER = 10;
  int QUOTED_STRING = 11;
  int SINGLE_QUOTED_STRING = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"within\"",
    "\"containing\"",
    "<NAME>",
    "<NUMBER>",
    "<QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "\"<\"",
    "\"/\"",
    "\">\"",
    "\"=\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"->\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\"!=\"",
  };

}
