version: '3.9'

services:

  node1:
    image: instituutnederlandsetaal/blacklab:latest
    environment:
      # Give JVM enough heap memory
      - JAVA_OPTS="-Xmx2G"
    command: /bin/bash /etc/blacklab/start-debug-server.sh
    ports:
      - "8081:8080"
    volumes:
      - /ssd3/linux-home-2022/opensonar/distrib-test/node1/index:/data/index/opensonar

  node2:
    image: instituutnederlandsetaal/blacklab:latest
    environment:
      # Give JVM enough heap memory
      - JAVA_OPTS="-Xmx2G"
    command: /bin/bash /etc/blacklab/start-debug-server.sh
    ports:
      - "8082:8080"
    volumes:
      - /ssd3/linux-home-2022/opensonar/distrib-test/node2/index:/data/index/opensonar

  node3:
    image: instituutnederlandsetaal/blacklab:latest
    environment:
      # Give JVM enough heap memory
      - JAVA_OPTS="-Xmx2G"
    command: /bin/bash /etc/blacklab/start-debug-server.sh
    ports:
      - "8083:8080"
    volumes:
      - /ssd3/linux-home-2022/opensonar/distrib-test/node3/index:/data/index/opensonar

  aggregator:
    profiles:
      - aggregator # We normally test the aggregator from the IDE, so only enable it if asked
    build:
      context: ..
      dockerfile: aggregator/Dockerfile
    volumes:
      - ./testdata/aggregator.yaml:/etc/blacklab/aggregator.yaml
    ports:
      - "8084:8080"
    depends_on:
      - node1
      - node2
