/* Generated By:JavaCC: Do not edit this line. ContextualQueryLanguageParserConstants.java */
package nl.inl.blacklab.queryParser.contextql;

public interface ContextualQueryLanguageParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int MULTI_LINE_COMMENT = 6;
  int AND = 7;
  int OR = 8;
  int NOT = 9;
  int PROX = 10;
  int IDENTIFIER = 11;
  int STRING = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"prox\"",
    "<IDENTIFIER>",
    "<STRING>",
    "\">\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"/\"",
  };

}
