# Docker Compose file for BlackLab with Solr.
# NOTE: in production, you probably want to run this with the
#       BlackLab proxy, to avoid opening Solr to the internet directly.

version: '3.9'

services:

  solr:
    build:
      context: ..
      dockerfile: solr/Dockerfile
