# Docker Compose dev override file for BlackLab with Solr.
# NOTE: this runs the container in JVM debug mode; not suitable for production!

version: '3.9'

services:

  solr:

    ports:
      # Solr runs on this port
      - "8983:8983"
      # Allow us to attach to the JVM using JDWP for remote debugging
      - "5005:5005"

    environment:
      # Enable JDWP remote debugging on port 5005
      - "SOLR_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      - "SOLR_HEAP=4g"

    volumes: 
      - E:/code/ivdnt/data/duct/blacklab-formats:/var/solr/data/formats
