# Docker Compose file for BlackLab with Solr.
# NOTE: this opens port 8983, but in production, you probably don't want that,
#       and instead run the BlackLab proxy to access Solr+BlackLab.

version: '3.9'

services:

  solr:
    build:
        context: ..
        dockerfile: solr/Dockerfile

    ports:

      # Solr runs on this port
      - "8983:8983"
