/*******************************************************************************
 * Copyright (c) 2010, 2012 Institute for Dutch Lexicology
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. CorpusQueryLanguageParser.java */
package nl.inl.blacklab.queryParser.corpusql;

import nl.inl.blacklab.search.TextPattern;
import nl.inl.blacklab.search.TextPatternAnd;
import nl.inl.blacklab.search.TextPatternOr;
import nl.inl.blacklab.search.TextPatternProperty;
import nl.inl.blacklab.search.TextPatternRegex;
import nl.inl.blacklab.search.sequences.TextPatternAnyToken;
import nl.inl.blacklab.search.sequences.TextPatternSequence;
import nl.inl.blacklab.search.sequences.TextPatternRepetition;

@SuppressWarnings("all")

public class CorpusQueryLanguageParser implements CorpusQueryLanguageParserConstants {

    public static void main(String[] args) throws Exception
    {
                CorpusQueryLanguageParser parser = new CorpusQueryLanguageParser(new java.io.StringReader(args[0]));
                parser.query();
    }

    private int num(Token t)
    {
        return Integer.parseInt(t.toString());
    }

    private String chopEnds(String regex)
    {
        if (regex.length() >= 2)
                return regex.substring(1, regex.length() - 1);
        throw new RuntimeException("Cannot chop slashes");
    }

    private TextPattern simplePattern(String str)
    {
        if (str.charAt(0) != '^')
            str = "^" + str;
        if (str.charAt(str.length() - 1) != '$')
            str += "$";

        return TextPatternRegex.getAppropriatePattern(str);
    }

    private String defaultProperty = "word";

    public void setDefaultProperty(String property) {
        defaultProperty = property;
    }

    public String getDefaultProperty() {
        return defaultProperty;
    }

    private TextPattern propertyClause(String prop, TextPattern value)
    {
        if (prop.equals(defaultProperty))
                return value; // default property
        return new TextPatternProperty(prop, value);
    }

// --- Grammar rules start here ---
  final public TextPattern query() throws ParseException {
        TextPattern query = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOTED_STRING:
    case 19:
    case 21:
    case 22:
      query = sequence();
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    jj_consume_token(0);
                {if (true) return query;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern sequence() throws ParseException {
        TextPattern first = null;
        TextPattern result = null;
    first = sequencePart();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOTED_STRING:
    case 10:
    case 17:
    case 18:
    case 19:
    case 21:
    case 22:
      result = sequenceRest(first);
      break;
    default:
      jj_la1[1] = jj_gen;
      ;
    }
                if (result == null)
                        {if (true) return first;}
                {if (true) return result;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern sequenceRest(TextPattern first) throws ParseException {
        Token op = null;
        TextPattern rest = null;
        Integer[] minMax = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOTED_STRING:
    case 19:
    case 21:
    case 22:
      rest = sequence();
                if (rest == null)
                        {if (true) return first;}
                {if (true) return new TextPatternSequence(first, rest);}
      break;
    case 10:
      minMax = sequenceOperator();
      rest = sequence();
                {if (true) return new TextPatternSequence(first, new TextPatternAnyToken(minMax[0], minMax[1]), rest);}
      break;
    case 17:
    case 18:
      op = booleanOperator();
      rest = sequence();
                if (op.toString().equals("&"))
                        {if (true) return new TextPatternAnd(first, rest);}
                {if (true) return new TextPatternOr(first, rest);}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Integer[] sequenceOperator() throws ParseException {
        Token t = null, t2 = null;
        Integer[] minMax = null;
    jj_consume_token(10);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 11:
    case 12:
    case 13:
    case 14:
      minMax = repetitionAmount();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
                if (minMax == null)
                        {if (true) return new Integer[]{1, 1};}
                if (minMax[1] == -1)
                        {if (true) throw new UnsupportedOperationException("Any-token without max not yet supported");}
                {if (true) return minMax;}
    throw new Error("Missing return statement in function");
  }

  final public Integer[] repetitionAmount() throws ParseException {
        Token t = null, t2 = null;
        Integer[] minMax = new Integer[2];
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 11:
      jj_consume_token(11);
                                              minMax[0] = 0; minMax[1] = -1; {if (true) return minMax;}
      break;
    case 12:
      jj_consume_token(12);
                                              minMax[0] = 1; minMax[1] = -1; {if (true) return minMax;}
      break;
    case 13:
      jj_consume_token(13);
                                              minMax[0] = 0; minMax[1] = 1; {if (true) return minMax;}
      break;
    default:
      jj_la1[5] = jj_gen;
      if (jj_2_1(3)) {
        jj_consume_token(14);
        t = jj_consume_token(NUMBER);
        jj_consume_token(15);
                                              minMax[0] = minMax[1] = num(t); {if (true) return minMax;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 14:
          jj_consume_token(14);
          t = jj_consume_token(NUMBER);
          jj_consume_token(16);
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case NUMBER:
            t2 = jj_consume_token(NUMBER);
            break;
          default:
            jj_la1[4] = jj_gen;
            ;
          }
          jj_consume_token(15);
                minMax[0] = num(t);
                if (t2 == null)
                        minMax[1] = -1;
                else
                        minMax[1] = num(t2);
                {if (true) return minMax;}
          break;
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Token booleanOperator() throws ParseException {
        Token t = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 17:
      t = jj_consume_token(17);
      break;
    case 18:
      t = jj_consume_token(18);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                           {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern sequencePart() throws ParseException {
        TextPattern m = null;
        Integer[] rep = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOTED_STRING:
    case 19:
    case 22:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUOTED_STRING:
      case 22:
        m = position();
        break;
      case 19:
        jj_consume_token(19);
        m = sequence();
        jj_consume_token(20);
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      if (jj_2_2(6)) {
        rep = repetitionAmount();
      } else {
        ;
      }
                if (rep != null)
                {
                        {if (true) return new TextPatternRepetition(m, rep[0], rep[1]);}
                }
                {if (true) return m;}
      break;
    case 21:
      jj_consume_token(21);
      m = sequencePart();
                                 {if (true) throw new UnsupportedOperationException("NOT operator not yet supported");}
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern position() throws ParseException {
        TextPattern m = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOTED_STRING:
      m = positionWord();
                                   {if (true) return m;}
      break;
    case 22:
      jj_consume_token(22);
      m = positionLong();
      jj_consume_token(23);
                                   {if (true) return m;}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern positionWord() throws ParseException {
        Token t = null;
    t = jj_consume_token(QUOTED_STRING);
                                 {if (true) return simplePattern(chopEnds(t.toString()));}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern positionLong() throws ParseException {
        TextPattern a = null, c = null;
        Token b = null;
    a = positionLongPart();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 17:
    case 18:
      b = booleanOperator();
      c = positionLong();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
                if (b == null)
                        {if (true) return a;}
                if (b.toString().equals("&"))
                        {if (true) return new TextPatternAnd(a, c);}
                {if (true) return new TextPatternOr(a, c);}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern positionLongPart() throws ParseException {
        TextPattern m = null;
    if (jj_2_3(3)) {
      m = attValuePair();
                                        {if (true) return m;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 19:
        jj_consume_token(19);
        m = positionLong();
        jj_consume_token(20);
                                        {if (true) return m;}
        break;
      case 21:
        jj_consume_token(21);
        m = positionLongPart();
                                        {if (true) throw new UnsupportedOperationException("NOT operator not yet supported!");}
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern attValuePair() throws ParseException {
        TextPattern v = null;
        Token t = null;
    if (jj_2_4(2)) {
      t = jj_consume_token(NAME);
      jj_consume_token(24);
      v = valuePart();
                                          {if (true) return propertyClause(t.toString(), v);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NAME:
        t = jj_consume_token(NAME);
        jj_consume_token(25);
        v = valuePart();
                                           {if (true) throw new UnsupportedOperationException("NOT operator not yet supported!");}
        break;
      case QUOTED_STRING:
      case 19:
      case 21:
        v = valuePart();
                                          {if (true) return v;}
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern value() throws ParseException {
        TextPattern a = null, c = null;
        Token b = null;
    if (jj_2_5(3)) {
      a = valuePart();
      b = booleanOperator();
      c = value();
                if (b.toString().equals("&"))
                        {if (true) return new TextPatternAnd(a, c);}
                {if (true) return new TextPatternOr(a, c);}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case QUOTED_STRING:
      case 19:
      case 21:
        a = valuePart();
                                          {if (true) return a;}
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern valuePart() throws ParseException {
        TextPattern m = null;
        Token t = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case QUOTED_STRING:
      t = jj_consume_token(QUOTED_STRING);
                                         {if (true) return simplePattern(chopEnds(t.toString()));}
      break;
    case 19:
      jj_consume_token(19);
      m = value();
      jj_consume_token(20);
                                         {if (true) return m;}
      break;
    case 21:
      jj_consume_token(21);
      m = valuePart();
                                         {if (true) throw new UnsupportedOperationException("NOT operator not yet supported!");}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3_3() {
    if (jj_3R_2()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(21)) return true;
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(19)) return true;
    if (jj_3R_5()) return true;
    if (jj_scan_token(20)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_1()) return true;
    return false;
  }

  private boolean jj_3R_3() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_12()) {
    jj_scanpos = xsp;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(QUOTED_STRING)) return true;
    return false;
  }

  private boolean jj_3R_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) return true;
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_3()) return true;
    if (jj_3R_4()) return true;
    if (jj_3R_5()) return true;
    return false;
  }

  private boolean jj_3R_5() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    }
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(14)) return true;
    if (jj_scan_token(NUMBER)) return true;
    if (jj_scan_token(16)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) jj_scanpos = xsp;
    if (jj_scan_token(15)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(14)) return true;
    if (jj_scan_token(NUMBER)) return true;
    if (jj_scan_token(15)) return true;
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_scan_token(13)) return true;
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(12)) return true;
    return false;
  }

  private boolean jj_3R_1() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_6()) {
    jj_scanpos = xsp;
    if (jj_3R_7()) {
    jj_scanpos = xsp;
    if (jj_3R_8()) {
    jj_scanpos = xsp;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3R_9()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_6() {
    if (jj_scan_token(11)) return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(25)) return true;
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_2() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_10()) {
    jj_scanpos = xsp;
    if (jj_3R_11()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(24)) return true;
    if (jj_3R_3()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public CorpusQueryLanguageParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[16];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x680200,0x6e0600,0x6e0600,0x7800,0x100,0x3800,0x4000,0x60000,0x480200,0x680200,0x400200,0x60000,0x280000,0x280280,0x280200,0x280200,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public CorpusQueryLanguageParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CorpusQueryLanguageParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CorpusQueryLanguageParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public CorpusQueryLanguageParser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new CorpusQueryLanguageParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public CorpusQueryLanguageParser(CorpusQueryLanguageParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CorpusQueryLanguageParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 16; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[26];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 16; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 26; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
