/*******************************************************************************
 * Copyright (c) 2010, 2012 Institute for Dutch Lexicology
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. CorpusQueryLanguageParserConstants.java */
package nl.inl.blacklab.queryParser.corpusql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CorpusQueryLanguageParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int QUOTED_STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<NAME>",
    "<NUMBER>",
    "<QUOTED_STRING>",
    "\"[]\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"!=\"",
  };

}
