name: Run the integration tests

on:
  push:
    branches: [ dev ]
  pull_request:
    # (PRs on all branches) branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run integration tests
      run: test/run.sh
