name: Run the integration tests

on:
  push:
    branches: [ dev ]
  pull_request:
    # No branch restriction, run integration tests on all PRs

jobs:

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [local-data, remote-data]

    steps:
    - uses: actions/checkout@v2
    - name: Download data
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        REMOTE_DATA_URL: ${{ secrets.REMOTE_DATA_URL }}
        REMOTE_CONFIGURATION_URL: ${{ secrets.REMOTE_CONFIGURATION_URL }}
      if: ${{ matrix.build_type == 'remote-data' && env.REMOTE_DATA_URL != '' }}
      run: test/download-data.sh
    - name: Run integration tests
      env:
        REMOTE_DATA_URL: ${{ secrets.REMOTE_DATA_URL }}
      if: ${{ matrix.build_type == 'local-data' || (matrix.build_type == 'remote-data' && env.REMOTE_DATA_URL != '') }}
      run: test/run-ci.sh
